name: paintbyword
channels:
  - pytorch
  - ostrokach-forge
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=10.2
  - pytorch=1.7.1
  - torchvision=0.8.2
  - mkl-include
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - numba
  - opencv
  - jupyter
  - ftfy
  - regex
  - nltk
  - cma
  - nodejs
  - pyyaml
  - mkl
  - tqdm
  - streamlit
  - pip
  - pip:
     - torchray
     - git+https://github.com/openai/CLIP.git
     - lpips
     - imageio
     - imageio-ffmpeg
